coverage:
  status:
    project:
      default: off
      shared-devtools:
        target: 80%
        flags: shared-devtools
      shared-common:
        target: 80%
        flags: shared-common
      shared-angular:
        target: 80%
        flags: shared-angular
      environment-common:
        target: 80%
        flags: environment-common
      environment-angular:
        target: 80%
        flags: environment-angular

flags:
  shared-devtools:
    paths:
      - coverage/package/shared/devtools/
  shared-common:
    paths:
      - coverage/package/shared/common/
  shared-angular:
    paths:
      - coverage/package/shared/common-angular/
  environment-common:
    paths:
      - coverage/package/environment/common/
  environment-angular:
    paths:
      - coverage/package/environment/angular/
